Pre check to find any AV on the machine
rackerlabs/GossAudit pull request #2
Opened 2022-05-25 09:24 UTC by karthikraos

2022-05-25 09:28 UTC, rsdoherty requested changes

2022-05-25 09:28 UTC, rsdoherty commented on Public/Get-GossEnrollmentReadiness.ps1
>          }
What AV products are we missing in `AV_SERVICES` that should be updated?

We should probably look to add this as well as the static check though, as L139 won't have a `DisplayName` property on the objects coming back from `Get-WmiObject`.

2022-05-25 09:35 UTC, karthikraos commented on Public/Get-GossEnrollmentReadiness.ps1
>          }
This story [VMM-64](https://rackspace.atlassian.net/browse/VMM-64) says we need to check if the VM has any antivirus (other than sophos) has already installed. So went with a generic antivirus filter.. Will remove the Display name...

2022-05-26 08:15 UTC, syedhaseebahmed approved these changes

2022-05-26 08:38 UTC, rsdoherty requested changes
A few very minor tweaks if we could!

Apologies to be so picky, but this is the first script our team has publically so we'd like to keep it in line with the standards of the code we write internally in terms of casing standards, using splats, and making warnings/errors contain detailed information.

I'll DM you the internal PowerShell scripting guidelines we follow for you to review, and thanks for the contribution!

2022-05-26 15:06 UTC, closed without merging